name: Release and Deploy API

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Google Cloud Credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.TF_DEPLOYER_KEY }}'

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.TF_DEPLOYER_KEY }}

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19
          extra_plugins: |
            @codedependant/semantic-release-docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy API on Google Cloud Platform
    runs-on: ubuntu-latest
    needs:
      - release
    if: needs.release.outputs.new_release_published == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: Google Cloud Credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.TF_DEPLOYER_KEY }}'

      - uses: hashicorp/setup-terraform@v2

      - run: terraform init
        working-directory: api/infrastructure

      - run: terraform apply -auto-approve
        working-directory: api/infrastructure
        env:
          TF_HTTP_PASSWORD: ${{ secrets.SHARED_STATE_PASSWORD }}
          TF_VAR_release_version: ${{ needs.release.outputs.new_release_version }}
